# WTF API

###
# baseURL
@baseURL = http://localhost:3000

###
# Random acronyms of given number
GET {{baseURL}}/auth/getToken/10X


###
# Random acronyms of given number
GET {{baseURL}}/wtf/acronym/10X


###
# Random acronyms of given number
GET {{baseURL}}/wtf/random/12


###
# Search acronyms with pagination query
GET {{baseURL}}/wtf/acronym?from=340&limit=10&search=A


###
# Add new acronym
POST {{baseURL}}/wtf/acronym
Content-Type: application/json

{
  "acronym"   : "test",
	"definition": "qwer1234"
}


###
# Update definition of given acronym
PUT {{baseURL}}/wtf/acronym/10X
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3JvbnltIjoiMTBYIiwiaWF0IjoxNjAyODEzNjYyLCJleHAiOjE2MDI4MTcyNjJ9.heMCJHCfoddfY4vXCEEX5XYWfvrakPwgNM0PfMa-YvY

{
	"definition": "Update testing"
}


###
# Update definition wtf/of given acronym
DELETE  {{baseURL}}/wtf/acronym/test