# WTF API

###
# baseURL
@baseURL = http://localhost:3000

###
# Random acronyms of given number
GET {{baseURL}}/auth/getToken/qwer1


###
# Random acronyms of given number

# GET {{baseURL}}/wtf/acronym/10X
GET {{baseURL}}/acronym/qwer1


###
# Random acronyms of given number

# GET {{baseURL}}/wtf/random/12
GET {{baseURL}}/random/12


###
# Search acronyms with pagination query

# GET {{baseURL}}/wtf/acronym?from=340&limit=10&search=A
GET {{baseURL}}/acronym?from=350&limit=10&search=A


###
# Add new acronym

# POST {{baseURL}}/wtf/acronym
POST {{baseURL}}/acronym
Content-Type: application/json

{
  "acronym"   : "qwer1",
	"definition": "qwer1"
}


###
# Update definition of given acronym

# PUT {{baseURL}}/wtf/acronym/10X
PUT {{baseURL}}/acronym/qwer1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3JvbnltIjoicXdlcjEiLCJpYXQiOjE2MDI4NzQ5MjUsImV4cCI6MTYwMjg3ODUyNX0.-oElnHlizVb2qG-_3xwJneC-IEiTpkwdXgWz8mzdpt8

{
	"definition": "Update testing"
}


###
# Update definition of given acronym

# DELETE  {{baseURL}}/wtf/acronym/test
DELETE  {{baseURL}}/acronym/qwer1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3JvbnltIjoicXdlcjEiLCJpYXQiOjE2MDI4NzQ5MjUsImV4cCI6MTYwMjg3ODUyNX0.-oElnHlizVb2qG-_3xwJneC-IEiTpkwdXgWz8mzdpt8